### ISSUE TITLE
Handle unreferenced objects

### ISSUE THREAD

**Issue by berndhahnebach** [yorikvanhavre/FreeCAD-NativeIFC#27]
ATM a unreferenced objects does not get a IfcObject in FreeCAD after import. Best would be if they get a own group right under the IfcProject object. Expand child does not work at all because there is no structure in the file. 

[unreferenced_box.ifc.txt](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/files/10855201/unreferenced_box.ifc.txt)

**Comment by yorikvanhavre** [comment]
Good point... We definitely want to support unreferenced objects. I guess we should start with an `get_unrefereced_objects(ifcfile)` function then we see how and where we render them...

**Comment by berndhahnebach** [comment]
do we have this in standard importer?

**Comment by yorikvanhavre** [comment]
No because the standard importer just import all of the objects. Here, we have different import strategies so we don't always render all objects.

But when we build the initial structure, we read all the shapes that are included into it. Maybe what we should do:

* get all products: ifcfile.by_type("IfcProduct")
* compare this list with the one we processed already
* if some of them aren't processed, that means they are out of the initial structure. pop a dialog asking the user if they want to import them
* if yes, process them individually and put them in a group

**Comment by Moult** [comment]
I'd recommend copying the strategy that BBIM uses to load elements, it's taken quite a bit of refinement over some time to learn what is valuable to load and what isn't.

**Comment by yorikvanhavre** [comment]
@Moult you told me once you could choose import strategies in BBIM, if you preferred to load everything, or only certain items, etc... I cannot find that back when loading an IFC file in Blender. Has it been removed?

**Comment by Moult** [comment]
@yorikvanhavre you have to "Enable Advanced Mode" when loading a project.

**Comment by yorikvanhavre** [comment]
ae1f64dcd4274896d1859d96f4d67ab950d3f13f now offers an option in the import dialog to load orphan objects. They are then placed into a "Orphans" group inside the project.

Now only thing missing is the ability to add a new object to that orphans group. That involves:

* Being able to create the orphans group if there isn't any
* Have the orphans group support dropping objects
* Extend the aggregate function so it can create an IFC object without relationship

More fundamentally, we'll need more of these special IFC root groups, for ex. to hold types, materials, etc... so we might as well make a new kind of object that supports drag and drop and other functionality we'll need in the future

**Comment by yorikvanhavre** [comment]
We can now consider this fixed by be713ee

I simplified a bit the handling of orphans... There is no more "orphans group", orphan objects simply appear under the project. So orphan objects are always loaded by default, but any new object will always be added to the project. In other words, you can load files with orphan objects, but you cannot create orphan objects (they will always be tied to a project).

I don't think it's desirable or advantageous to create orphan objects, or let's say there is no advantage to leave them unrelated to the project. If such necessity arises, though, it wouldn't be much to adapt.
