### ISSUE TITLE
[Issue] Sync object visibility between tree-view and 3d-view

### ISSUE THREAD

**Issue by balrobs** [yorikvanhavre/FreeCAD-NativeIFC#41]
Steps to reproduce:

1. Import MyHouse.ifc (created with Blenderbim)
2. Select Slab001 in the tree view and press space bar to hide the slab
3. Notice that Slab001 is hidden in the 3d view and is greyed out in the tree view. So far so good!
4. The storey object EG is marked for a recompute (???) Do a recompute.
5. Now select Slab001 in the tree view and press space bar to show the slab
6. The slab turns visible in the 3d view but stays greyed out in the tree view. No recompute visible (???)

[MyHouse.ifc.txt](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/files/11334694/MyHouse.ifc.txt)

**Comment by yorikvanhavre** [comment]
This is a known problem when using the Group extension. I can't find back where it's discussed on the forum... The BuildingPart object suffers the same problem).

I think we should simply stop using the group extension and code things ourselves. Most of this is actually done already since we implemented custom drag/droppping operations.

Rest that needs to be done is:

* creating the Group property manually
* implement claimChildren()
* maybe (not sure) functionality to switch the visibility of children when switching object visibility
* remove workaround code at https://github.com/yorikvanhavre/FreeCAD-NativeIFC/blob/main/ifc_tools.py#L708

**Comment by yorikvanhavre** [comment]
The above problem is solved by [8b93a15](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/commit/8b93a15e98a6fe21bdb997e0e92676246c34be26)
However, objects with a Group property still build a coin representation automatically from their children, no matter if using the extension or not. This will be hard to track...
So at the moment the 1x1x1 shape trick at https://github.com/yorikvanhavre/FreeCAD-NativeIFC/blob/main/ifc_tools.py#L702 is still used. I'll leave this open until I find a better idea...

**Comment by yorikvanhavre** [comment]
Investigating further, even if the Group property is renamed to something else, they still build a coin representation from their children.

**Comment by yorikvanhavre** [comment]
This is now solved in FreeCAD main codebranch
